/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Basic_message: typeof import('./src/components/home/message/Basic_message.vue')['default']
    Chat: typeof import('./src/components/home/chat.vue')['default']
    Chatfolders: typeof import('./src/components/home/chatfolders.vue')['default']
    Chatlistmessage: typeof import('./src/components/home/chat/chatlistmessage.vue')['default']
    ChatWindow: typeof import('./src/components/home/chat/ChatWindow.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    Rightcontents: typeof import('./src/components/home/chat/rightcontents.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/home/search.vue')['default']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    TDropdownItem: typeof import('tdesign-vue-next')['DropdownItem']
    TDropdownMenu: typeof import('tdesign-vue-next')['DropdownMenu']
    Test: typeof import('./src/components/test.vue')['default']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
